name: 💡 Feature Request
description: Describe what you'd like to see in Archi
title: "[Feature Request] "
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe the feature you'd like to see implemented in Archi. Please provide as much detail as possible - use cases, steps to fulfil the task, mockups, etc.
      placeholder: |
        Describe the feature you'd like to see implemented in Archi.
    validations:
      required: true
